/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package coffee_shop;

import com.mysql.jdbc.interceptors.SessionAssociationInterceptor;
import java.awt.event.ActionEvent;
import java.awt.event.KeyEvent;
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.ResultSet;
import java.sql.Statement;
import java.util.ArrayList;
import java.util.concurrent.ThreadLocalRandom;
import javax.swing.ImageIcon;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author HALO44O
 */
public class billpage extends javax.swing.JFrame {

   
    public billpage() {
        initComponents();
          UserTableDataSetter(); 
           jLabel11.setVisible(false);
    }

      void UserTableDataSetter(){
        //db connection
            String url = "jdbc:mysql://localhost:3306/coffee_shop";
            String user =  "root";
            String password = "1234";  
            try {
                Class.forName("com.mysql.jdbc.Driver");       
                Connection con = DriverManager.getConnection(url, user, password);
                Statement st = con.createStatement(); 
                ResultSet result = st.executeQuery("SELECT * FROM items");

                DefaultTableModel table = (DefaultTableModel) item_table.getModel();
                
                while(result.next()){
                    ArrayList list = new ArrayList();                    
                    list.add(result.getString("itemname"));
                    list.add(result.getString("price"));
                    
                    
                    table.addRow(list.toArray());
                    
                }              
                
            } catch (Exception e) {
                System.out.println(e);
            }
    }
    
    void nexttotal(){
        
       String totalold =jLabel8.getText();
        String totalmain =jLabel3.getText();
        
        
 int oldtotal = Integer.parseInt(totalold);
  int maintotal = Integer.parseInt(totalmain);
 
 
 int sum = oldtotal + maintotal;
  String nexttotal=String.valueOf(sum);
  jLabel3.setText(nexttotal);
    }
    
    public void billtable(){
        String billmain2 = jLabel3.getText();
         String billmain3 = jLabel8.getText();
    
     DefaultTableModel model1 = new DefaultTableModel();
     model1 =(DefaultTableModel)bill_table.getModel();
     
        if (billmain2.isEmpty()) {
           
              model1.addRow(new Object[] {
         item_na.getText(),
         price_bill.getText(),
         qun_bill.getText(),
         jLabel8.getText()
         
     }); 
         jLabel3.setText("0");     
        }else{
     
     model1.addRow(new Object[] {
         item_na.getText(),
         price_bill.getText(),
         qun_bill.getText(),
          jLabel8.getText()
     });  
        }
    }
    
    public void clearbill(){
        item_na.setText("");
         price_bill.setText("");
         qun_bill.setText("");
       
    }
    
    public void cashex(){
    
     String tootalold =jLabel3.getText();
        String cash =jTextField1.getText();
        
        
 int ooldtotal = Integer.parseInt(tootalold);
  int hiscash = Integer.parseInt(cash);
     
        
    int min = hiscash - ooldtotal;
    String last =String.valueOf(min);
    System.out.print(min);
    jLabel5.setText(last);
    
    }
    
    public void tableclear(){
    
        DefaultTableModel model = (DefaultTableModel) bill_table.getModel();
        model.setRowCount(0);
    
    }
    
   public  void billnumberset(){
   int billnb = ThreadLocalRandom.current().nextInt(000000000000,999999999);
   String billnbtxt = String.valueOf(billnb);
   System.out.println(billnbtxt);
           
   }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        qun_bill = new javax.swing.JTextField();
        item_na = new javax.swing.JLabel();
        price_bill = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jTextField1 = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        item_table = new javax.swing.JTable();
        jScrollPane3 = new javax.swing.JScrollPane();
        bill_table = new javax.swing.JTable();
        jLabel2 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);

        jPanel1.setLayout(null);

        qun_bill.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        qun_bill.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        qun_bill.setBorder(null);
        qun_bill.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                qun_billActionPerformed(evt);
            }
        });
        qun_bill.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                qun_billKeyReleased(evt);
            }
        });
        jPanel1.add(qun_bill);
        qun_bill.setBounds(430, 240, 110, 70);

        item_na.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        item_na.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jPanel1.add(item_na);
        item_na.setBounds(240, 134, 300, 60);

        price_bill.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jPanel1.add(price_bill);
        price_bill.setBounds(160, 240, 130, 70);

        jLabel3.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel3.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jPanel1.add(jLabel3);
        jLabel3.setBounds(250, 550, 260, 50);

        jTextField1.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jTextField1.setHorizontalAlignment(javax.swing.JTextField.LEFT);
        jTextField1.setBorder(null);
        jTextField1.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                jTextField1KeyReleased(evt);
            }
        });
        jPanel1.add(jTextField1);
        jTextField1.setBounds(260, 620, 240, 40);

        jLabel5.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel5.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jPanel1.add(jLabel5);
        jLabel5.setBounds(254, 684, 250, 50);

        jPanel2.setLayout(null);

        item_table.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        item_table.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Item", "Price"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        item_table.setRowHeight(32);
        item_table.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                item_tableMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(item_table);

        jPanel2.add(jScrollPane1);
        jScrollPane1.setBounds(0, 0, 670, 660);

        bill_table.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        bill_table.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Item Name", "Price for Unit", "Quantity", "All price"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        bill_table.setRowHeight(32);
        bill_table.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                bill_tableMouseClicked(evt);
            }
        });
        jScrollPane3.setViewportView(bill_table);

        jPanel2.add(jScrollPane3);
        jScrollPane3.setBounds(0, 0, 670, 660);

        jPanel1.add(jPanel2);
        jPanel2.setBounds(660, 80, 670, 660);

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/IMG/bill_bt_page1.png"))); // NOI18N
        jLabel2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel2MouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jLabel2MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                jLabel2MouseExited(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                jLabel2MousePressed(evt);
            }
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                jLabel2MouseReleased(evt);
            }
        });
        jPanel1.add(jLabel2);
        jLabel2.setBounds(840, 10, 180, 60);

        jLabel4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/IMG/item_bt_page1.png"))); // NOI18N
        jLabel4.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel4MouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jLabel4MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                jLabel4MouseExited(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                jLabel4MousePressed(evt);
            }
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                jLabel4MouseReleased(evt);
            }
        });
        jPanel1.add(jLabel4);
        jLabel4.setBounds(660, 10, 180, 60);

        jLabel6.setIcon(new javax.swing.ImageIcon(getClass().getResource("/IMG/add_bill.png"))); // NOI18N
        jLabel6.setText("jLabel6");
        jLabel6.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel6MouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jLabel6MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                jLabel6MouseExited(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                jLabel6MousePressed(evt);
            }
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                jLabel6MouseReleased(evt);
            }
        });
        jPanel1.add(jLabel6);
        jLabel6.setBounds(80, 340, 440, 90);

        jLabel7.setIcon(new javax.swing.ImageIcon(getClass().getResource("/IMG/bill_bill.png"))); // NOI18N
        jLabel7.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel7MouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jLabel7MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                jLabel7MouseExited(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                jLabel7MousePressed(evt);
            }
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                jLabel7MouseReleased(evt);
            }
        });
        jPanel1.add(jLabel7);
        jLabel7.setBounds(80, 430, 450, 80);

        jLabel9.setIcon(new javax.swing.ImageIcon(getClass().getResource("/IMG/cut.png"))); // NOI18N
        jLabel9.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel9MouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jLabel9MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                jLabel9MouseExited(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                jLabel9MousePressed(evt);
            }
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                jLabel9MouseReleased(evt);
            }
        });
        jPanel1.add(jLabel9);
        jLabel9.setBounds(1330, 0, 40, 40);

        jLabel10.setIcon(new javax.swing.ImageIcon(getClass().getResource("/IMG/newitem.png"))); // NOI18N
        jLabel10.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel10MouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jLabel10MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                jLabel10MouseExited(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                jLabel10MousePressed(evt);
            }
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                jLabel10MouseReleased(evt);
            }
        });
        jPanel1.add(jLabel10);
        jLabel10.setBounds(90, 10, 450, 80);

        jLabel11.setIcon(new javax.swing.ImageIcon(getClass().getResource("/IMG/delete1.png"))); // NOI18N
        jLabel11.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel11MouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jLabel11MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                jLabel11MouseExited(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                jLabel11MousePressed(evt);
            }
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                jLabel11MouseReleased(evt);
            }
        });
        jPanel1.add(jLabel11);
        jLabel11.setBounds(80, 350, 440, 70);

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/IMG/bill_page.png"))); // NOI18N
        jLabel1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel1MouseClicked(evt);
            }
        });
        jLabel1.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                jLabel1KeyPressed(evt);
            }
        });
        jPanel1.add(jLabel1);
        jLabel1.setBounds(0, 0, 1370, 770);

        jLabel8.setText("0");
        jPanel1.add(jLabel8);
        jLabel8.setBounds(540, 734, 60, 30);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 1366, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 768, Short.MAX_VALUE)
        );

        java.awt.Dimension screenSize = java.awt.Toolkit.getDefaultToolkit().getScreenSize();
        setBounds((screenSize.width-1366)/2, (screenSize.height-768)/2, 1366, 768);
    }// </editor-fold>//GEN-END:initComponents

    private void qun_billActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_qun_billActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_qun_billActionPerformed

    private void item_tableMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_item_tableMouseClicked
        DefaultTableModel table= (DefaultTableModel) item_table.getModel();
         int selectedRow = item_table.getSelectedRow();
         
         item_na.setText(table.getValueAt(selectedRow, 0).toString());
         price_bill.setText(table.getValueAt(selectedRow, 1).toString());
         qun_bill.requestFocus();
         
    }//GEN-LAST:event_item_tableMouseClicked

    private void jLabel2MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel2MouseEntered
        ImageIcon ii = new ImageIcon(getClass().getResource("/IMG/bill_bt_page2.png"));
        jLabel2.setIcon(ii);
    }//GEN-LAST:event_jLabel2MouseEntered

    private void jLabel2MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel2MouseExited
        ImageIcon ii = new ImageIcon(getClass().getResource("/IMG/bill_bt_page1.png"));
        jLabel2.setIcon(ii);
    }//GEN-LAST:event_jLabel2MouseExited

    private void jLabel2MousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel2MousePressed
         ImageIcon ii = new ImageIcon(getClass().getResource("/IMG/bill_bt_page.png"));
        jLabel2.setIcon(ii);
    }//GEN-LAST:event_jLabel2MousePressed

    private void jLabel2MouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel2MouseReleased
         ImageIcon ii = new ImageIcon(getClass().getResource("/IMG/bill_bt_page1.png"));
        jLabel2.setIcon(ii);
    }//GEN-LAST:event_jLabel2MouseReleased

    private void jLabel2MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel2MouseClicked
        ImageIcon ii = new ImageIcon(getClass().getResource("/IMG/item_bt_page2.png"));
        jLabel4.setIcon(ii);
        
         jLabel2.setVisible(false);
         jLabel4.setVisible(true);
         jScrollPane3.setVisible(true);
         jScrollPane1.setVisible(false);
         jLabel6.setVisible(false);
         jLabel11.setVisible(true);
    }//GEN-LAST:event_jLabel2MouseClicked

    private void jLabel4MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel4MouseEntered
        ImageIcon ii = new ImageIcon(getClass().getResource("/IMG/item_bt_page3.png"));
        jLabel4.setIcon(ii);
    }//GEN-LAST:event_jLabel4MouseEntered

    private void jLabel4MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel4MouseExited
       ImageIcon ii = new ImageIcon(getClass().getResource("/IMG/item_bt_page2.png"));
        jLabel4.setIcon(ii);
    }//GEN-LAST:event_jLabel4MouseExited

    private void jLabel4MousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel4MousePressed
       ImageIcon ii = new ImageIcon(getClass().getResource("/IMG/item_bt_page1.png"));
        jLabel4.setIcon(ii);
    }//GEN-LAST:event_jLabel4MousePressed

    private void jLabel4MouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel4MouseReleased
       ImageIcon ii = new ImageIcon(getClass().getResource("/IMG/item_bt_page3.png"));
        jLabel4.setIcon(ii);
    }//GEN-LAST:event_jLabel4MouseReleased

    private void jLabel4MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel4MouseClicked
        ImageIcon ii = new ImageIcon(getClass().getResource("/IMG/bill_bt_page1.png"));
        jLabel2.setIcon(ii);
        
        jLabel2.setVisible(true);
        jLabel4.setVisible(false);
        jScrollPane3.setVisible(false);
        jScrollPane1.setVisible(true);
        jLabel6.setVisible(true);
        jLabel11.setVisible(false);
    }//GEN-LAST:event_jLabel4MouseClicked

    private void jLabel6MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel6MouseEntered
       ImageIcon ii = new ImageIcon(getClass().getResource("/IMG/add_bill2.png"));
        jLabel6.setIcon(ii);
    }//GEN-LAST:event_jLabel6MouseEntered

    private void jLabel1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel1MouseClicked
       item_na.setText("");
       price_bill.setText("");
       qun_bill.setText("");
       
       
    }//GEN-LAST:event_jLabel1MouseClicked

    private void jLabel6MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel6MouseExited
        ImageIcon ii = new ImageIcon(getClass().getResource("/IMG/add_bill.png"));
        jLabel6.setIcon(ii);
    }//GEN-LAST:event_jLabel6MouseExited

    private void jLabel6MousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel6MousePressed
         ImageIcon ii = new ImageIcon(getClass().getResource("/IMG/add_bill3.png"));
        jLabel6.setIcon(ii);
    }//GEN-LAST:event_jLabel6MousePressed

    private void jLabel6MouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel6MouseReleased
          ImageIcon ii = new ImageIcon(getClass().getResource("/IMG/add_bill2.png"));
        jLabel6.setIcon(ii);
    }//GEN-LAST:event_jLabel6MouseReleased

    private void jLabel7MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel7MouseEntered
        ImageIcon ii = new ImageIcon(getClass().getResource("/IMG/bill_bill2.png"));
        jLabel7.setIcon(ii);
    }//GEN-LAST:event_jLabel7MouseEntered

    private void jLabel7MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel7MouseExited
       ImageIcon ii = new ImageIcon(getClass().getResource("/IMG/bill_bill.png"));
        jLabel7.setIcon(ii);
    }//GEN-LAST:event_jLabel7MouseExited

    private void jLabel7MousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel7MousePressed
        ImageIcon ii = new ImageIcon(getClass().getResource("/IMG/bill_bill3.png"));
        jLabel7.setIcon(ii);
    }//GEN-LAST:event_jLabel7MousePressed

    private void jLabel7MouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel7MouseReleased
       ImageIcon ii = new ImageIcon(getClass().getResource("/IMG/bill_bill2.png"));
        jLabel7.setIcon(ii);
    }//GEN-LAST:event_jLabel7MouseReleased
    
    private void jLabel6MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel6MouseClicked
    
        
        
      
        
          String name = item_na.getText();
         String price = price_bill.getText();
         String quantity = qun_bill.getText();
          if(quantity.isEmpty()){
              
              billpage.jLabel6.setVisible(false);
              billpage.jLabel7.setVisible(false);
              billpage.item_table.setVisible(false);
                 quantity_billpage_error jf2 = new   quantity_billpage_error();
                 jf2.show(); 
            
          }else{
          
                int x = Integer.parseInt(price); //first arguments.
         int y = Integer.parseInt(quantity); //second arguments.
         
         int itemco = x * y;
         String itemcoo=String.valueOf(itemco);
         
        jLabel8.setText(itemcoo);
         
          billtable();
           nexttotal();
          clearbill();
          billnumberset();
          
          }
         
         
       
    }//GEN-LAST:event_jLabel6MouseClicked

    private void jLabel7MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel7MouseClicked
        cashex();
        
    }//GEN-LAST:event_jLabel7MouseClicked

    private void jLabel1KeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jLabel1KeyPressed
     
    }//GEN-LAST:event_jLabel1KeyPressed

    private void jTextField1KeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTextField1KeyReleased
         if (evt.getKeyCode()==KeyEvent.VK_ALT){
         tableclear();
         jLabel3.setText("");
         jLabel8.setText("0");
         jTextField1.setText("");
         jLabel5.setText("");
         
      }
    }//GEN-LAST:event_jTextField1KeyReleased

    private void jLabel9MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel9MouseEntered
          ImageIcon ii = new ImageIcon(getClass().getResource("/IMG/cut2.png"));
        jLabel9.setIcon(ii);
    }//GEN-LAST:event_jLabel9MouseEntered

    private void jLabel9MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel9MouseExited
         ImageIcon ii = new ImageIcon(getClass().getResource("/IMG/cut.png"));
        jLabel9.setIcon(ii);
    }//GEN-LAST:event_jLabel9MouseExited

    private void jLabel9MousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel9MousePressed
        ImageIcon ii = new ImageIcon(getClass().getResource("/IMG/cut3.png"));
        jLabel9.setIcon(ii);
    }//GEN-LAST:event_jLabel9MousePressed

    private void jLabel9MouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel9MouseReleased
         ImageIcon ii = new ImageIcon(getClass().getResource("/IMG/cut2.png"));
        jLabel9.setIcon(ii);
    }//GEN-LAST:event_jLabel9MouseReleased

    private void jLabel9MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel9MouseClicked
       System.exit(0);
    }//GEN-LAST:event_jLabel9MouseClicked

    private void qun_billKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_qun_billKeyReleased
        if (evt.getKeyCode()==KeyEvent.VK_ENTER){
            
          String name = item_na.getText();
         String price = price_bill.getText();
         String quantity = qun_bill.getText();
          if(quantity.isEmpty()){
          
               
              billpage.jLabel6.setVisible(false);
              billpage.jLabel7.setVisible(false);
              billpage.item_table.setVisible(false);
                 quantity_billpage_error jf2 = new   quantity_billpage_error();
                 jf2.show(); 
            
              
          }else{
          
                int x = Integer.parseInt(price); //first arguments.
         int y = Integer.parseInt(quantity); //second arguments.
         
         int itemco = x * y;
         String itemcoo=String.valueOf(itemco);
         
        jLabel8.setText(itemcoo);
         
          billtable();
           nexttotal();
          clearbill();
          
          
          
          
          }
         
            
        }
    }//GEN-LAST:event_qun_billKeyReleased

    private void jLabel10MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel10MouseEntered
       ImageIcon ii = new ImageIcon(getClass().getResource("/IMG/newitem2.png"));
        jLabel10.setIcon(ii);
    }//GEN-LAST:event_jLabel10MouseEntered

    private void jLabel10MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel10MouseExited
        ImageIcon ii = new ImageIcon(getClass().getResource("/IMG/newitem.png"));
        jLabel10.setIcon(ii);
    }//GEN-LAST:event_jLabel10MouseExited

    private void jLabel10MousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel10MousePressed
        ImageIcon ii = new ImageIcon(getClass().getResource("/IMG/newitem3.png"));
        jLabel10.setIcon(ii);
    }//GEN-LAST:event_jLabel10MousePressed

    private void jLabel10MouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel10MouseReleased
        ImageIcon ii = new ImageIcon(getClass().getResource("/IMG/newitem2.png"));
        jLabel10.setIcon(ii);
    }//GEN-LAST:event_jLabel10MouseReleased

    private void jLabel10MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel10MouseClicked
       item_add jf2 = new   item_add();
                 jf2.show(); 
                 dispose();
    }//GEN-LAST:event_jLabel10MouseClicked

    private void jLabel11MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel11MouseEntered
        ImageIcon ii = new ImageIcon(getClass().getResource("/IMG/delete2.png"));
        jLabel11.setIcon(ii);
    }//GEN-LAST:event_jLabel11MouseEntered

    private void jLabel11MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel11MouseExited
       ImageIcon ii = new ImageIcon(getClass().getResource("/IMG/delete1.png"));
       jLabel11.setIcon(ii);
    }//GEN-LAST:event_jLabel11MouseExited

    private void jLabel11MousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel11MousePressed
      ImageIcon ii = new ImageIcon(getClass().getResource("/IMG/delete3.png"));
        jLabel11.setIcon(ii);
    }//GEN-LAST:event_jLabel11MousePressed

    private void jLabel11MouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel11MouseReleased
       ImageIcon ii = new ImageIcon(getClass().getResource("/IMG/delete2.png"));
        jLabel11.setIcon(ii);
    }//GEN-LAST:event_jLabel11MouseReleased

    private void bill_tableMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_bill_tableMouseClicked
     DefaultTableModel table= (DefaultTableModel) bill_table.getModel();
         int selectedRow = bill_table.getSelectedRow();
         
         item_na.setText(table.getValueAt(selectedRow, 0).toString());
         price_bill.setText(table.getValueAt(selectedRow, 1).toString());
         qun_bill.setText(table.getValueAt(selectedRow, 2).toString());
    }//GEN-LAST:event_bill_tableMouseClicked

        public void actionPerformed(ActionEvent arg0) {
            
  
        }
    
    private void jLabel11MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel11MouseClicked
     DefaultTableModel table= (DefaultTableModel) bill_table.getModel();
        
               if (bill_table.getSelectedRow()!= -1) {
            // remove selected row from the model
            table.removeRow(bill_table.getSelectedRow());
        }
    
            
    }//GEN-LAST:event_jLabel11MouseClicked
    
    private void TotalSet(){
       int total = 0;

       
    }
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(billpage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(billpage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(billpage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(billpage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new billpage().setVisible(true);
            }
        });
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTable bill_table;
    private javax.swing.JLabel item_na;
    public static javax.swing.JTable item_table;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    public static javax.swing.JLabel jLabel6;
    public static javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JLabel price_bill;
    private javax.swing.JTextField qun_bill;
    // End of variables declaration//GEN-END:variables
}
