/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package coffee_shop;

import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import java.sql.Connection;
 
import java.awt.event.KeyEvent;
import java.util.Date;
import java.sql.DriverManager;
import java.sql.ResultSet;
import java.sql.Statement;
import java.text.SimpleDateFormat;
import java.util.ArrayList;
import javax.swing.ImageIcon;
import javax.swing.JOptionPane;
import javax.swing.Timer;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author HALO44O
 */
public class item_add extends javax.swing.JFrame {

    /**
     * Creates new form item_add
     */
    public item_add() {
        initComponents();
        dt();
         times();
         UserTableDataSetter(); 
    }
  
    
      void UserTableDataSetter(){
        //db connection
            String url = "jdbc:mysql://localhost:3306/coffee_shop";
            String user =  "root";
            String password = "1234";  
            try {
                Class.forName("com.mysql.jdbc.Driver");       
                Connection con = DriverManager.getConnection(url, user, password);
                Statement st = con.createStatement(); 
                ResultSet result = st.executeQuery("SELECT * FROM items");

                DefaultTableModel table = (DefaultTableModel) item_table.getModel();
                
                while(result.next()){
                    ArrayList list = new ArrayList();                    
                    list.add(result.getString("itemname"));
                    list.add(result.getString("price"));
                    
                    
                    table.addRow(list.toArray());
                    
                }              
                
            } catch (Exception e) {
                System.out.println(e);
            }
    }
    
    void UserTableDataClear(){
        DefaultTableModel table = (DefaultTableModel) item_table.getModel();
        
        int count = table.getRowCount();
        for(int i = 0; i < count ;i++){
            table.removeRow(0);
        }
        
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    
      public void dt(){
    
     Date d =new Date();
     SimpleDateFormat sdf = new SimpleDateFormat("yyyy-MM-dd");
     String dd = sdf.format(d);
     date.setText(dd);             
    
    }
      
     Timer t ;
     SimpleDateFormat st;
      
    public void times(){
       
        
        t =new Timer(0,new ActionListener() {

            @Override
            public void actionPerformed(ActionEvent e) {
                //throw new UnsupportedOperationException("Not supported yet.");
           Date dt =new Date();
           st = new SimpleDateFormat("hh:mm:ss a");
           String tt = st.format(dt);
           times.setText(tt);
           
           
            }
        });
        t.start();
    }
    
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        itname = new javax.swing.JTextField();
        itprice = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        item_table = new javax.swing.JTable();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        times = new javax.swing.JLabel();
        date = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);

        jPanel1.setLayout(null);

        itname.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        itname.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        itname.setBorder(null);
        itname.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                itnameKeyReleased(evt);
            }
        });
        jPanel1.add(itname);
        itname.setBounds(210, 190, 320, 60);

        itprice.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        itprice.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        itprice.setBorder(null);
        jPanel1.add(itprice);
        itprice.setBounds(160, 320, 370, 60);

        item_table.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        item_table.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Item_name", "price"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        item_table.setGridColor(new java.awt.Color(102, 0, 204));
        item_table.setRowHeight(30);
        item_table.setSelectionBackground(new java.awt.Color(99, 74, 158));
        item_table.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                item_tableMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(item_table);

        jPanel1.add(jScrollPane1);
        jScrollPane1.setBounds(662, 72, 650, 650);

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/IMG/save1.png"))); // NOI18N
        jLabel2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel2MouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jLabel2MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                jLabel2MouseExited(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                jLabel2MousePressed(evt);
            }
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                jLabel2MouseReleased(evt);
            }
        });
        jPanel1.add(jLabel2);
        jLabel2.setBounds(70, 410, 460, 90);

        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/IMG/clearlg1.png"))); // NOI18N
        jLabel3.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel3MouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jLabel3MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                jLabel3MouseExited(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                jLabel3MousePressed(evt);
            }
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                jLabel3MouseReleased(evt);
            }
        });
        jPanel1.add(jLabel3);
        jLabel3.setBounds(70, 500, 440, 80);

        jLabel4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/IMG/delete1.png"))); // NOI18N
        jLabel4.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel4MouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jLabel4MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                jLabel4MouseExited(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                jLabel4MousePressed(evt);
            }
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                jLabel4MouseReleased(evt);
            }
        });
        jPanel1.add(jLabel4);
        jLabel4.setBounds(70, 580, 440, 90);

        jLabel6.setIcon(new javax.swing.ImageIcon(getClass().getResource("/IMG/update1.png"))); // NOI18N
        jLabel6.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel6MouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jLabel6MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                jLabel6MouseExited(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                jLabel6MousePressed(evt);
            }
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                jLabel6MouseReleased(evt);
            }
        });
        jPanel1.add(jLabel6);
        jLabel6.setBounds(70, 670, 440, 80);

        jLabel5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/IMG/cut.png"))); // NOI18N
        jLabel5.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel5MouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jLabel5MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                jLabel5MouseExited(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                jLabel5MousePressed(evt);
            }
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                jLabel5MouseReleased(evt);
            }
        });
        jPanel1.add(jLabel5);
        jLabel5.setBounds(1330, 0, 40, 40);

        times.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        times.setText("0");
        jPanel1.add(times);
        times.setBounds(430, 0, 130, 30);

        date.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        date.setText("0");
        jPanel1.add(date);
        date.setBounds(270, 0, 140, 30);

        jLabel7.setIcon(new javax.swing.ImageIcon(getClass().getResource("/IMG/back1.png"))); // NOI18N
        jLabel7.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel7MouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jLabel7MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                jLabel7MouseExited(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                jLabel7MousePressed(evt);
            }
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                jLabel7MouseReleased(evt);
            }
        });
        jPanel1.add(jLabel7);
        jLabel7.setBounds(20, 10, 50, 50);

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/IMG/item_add.png"))); // NOI18N
        jPanel1.add(jLabel1);
        jLabel1.setBounds(0, 0, 1370, 770);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 1366, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 768, Short.MAX_VALUE)
        );

        java.awt.Dimension screenSize = java.awt.Toolkit.getDefaultToolkit().getScreenSize();
        setBounds((screenSize.width-1366)/2, (screenSize.height-768)/2, 1366, 768);
    }// </editor-fold>//GEN-END:initComponents

    private void jLabel2MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel2MouseEntered
      ImageIcon ii = new ImageIcon(getClass().getResource("/IMG/save2.png"));
        jLabel2.setIcon(ii);
    }//GEN-LAST:event_jLabel2MouseEntered

    private void jLabel2MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel2MouseExited
       ImageIcon ii = new ImageIcon(getClass().getResource("/IMG/save1.png"));
        jLabel2.setIcon(ii);
    }//GEN-LAST:event_jLabel2MouseExited

    private void jLabel2MousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel2MousePressed
      ImageIcon ii = new ImageIcon(getClass().getResource("/IMG/save3.png"));
        jLabel2.setIcon(ii);
    }//GEN-LAST:event_jLabel2MousePressed

    private void jLabel2MouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel2MouseReleased
      ImageIcon ii = new ImageIcon(getClass().getResource("/IMG/save2.png"));
        jLabel2.setIcon(ii);
    }//GEN-LAST:event_jLabel2MouseReleased

    private void jLabel3MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel3MouseEntered
     ImageIcon ii = new ImageIcon(getClass().getResource("/IMG/clearlg2.png"));
        jLabel3.setIcon(ii);
    }//GEN-LAST:event_jLabel3MouseEntered

    private void jLabel3MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel3MouseExited
      ImageIcon ii = new ImageIcon(getClass().getResource("/IMG/clearlg1.png"));
        jLabel3.setIcon(ii);
    }//GEN-LAST:event_jLabel3MouseExited

    private void jLabel3MousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel3MousePressed
       ImageIcon ii = new ImageIcon(getClass().getResource("/IMG/clearlg3.png"));
        jLabel3.setIcon(ii);
    }//GEN-LAST:event_jLabel3MousePressed

    private void jLabel3MouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel3MouseReleased
         ImageIcon ii = new ImageIcon(getClass().getResource("/IMG/clearlg2.png"));
        jLabel3.setIcon(ii);
    }//GEN-LAST:event_jLabel3MouseReleased

    private void jLabel4MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel4MouseEntered
       ImageIcon ii = new ImageIcon(getClass().getResource("/IMG/delete2.png"));
        jLabel4.setIcon(ii);
    }//GEN-LAST:event_jLabel4MouseEntered

    private void jLabel4MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel4MouseExited
         ImageIcon ii = new ImageIcon(getClass().getResource("/IMG/delete1.png"));
        jLabel4.setIcon(ii);
    }//GEN-LAST:event_jLabel4MouseExited

    private void jLabel4MousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel4MousePressed
         ImageIcon ii = new ImageIcon(getClass().getResource("/IMG/delete3.png"));
        jLabel4.setIcon(ii);
    }//GEN-LAST:event_jLabel4MousePressed

    private void jLabel4MouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel4MouseReleased
        ImageIcon ii = new ImageIcon(getClass().getResource("/IMG/delete2.png"));
        jLabel4.setIcon(ii);
    }//GEN-LAST:event_jLabel4MouseReleased

    private void jLabel6MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel6MouseEntered
         ImageIcon ii = new ImageIcon(getClass().getResource("/IMG/update2.png"));
        jLabel6.setIcon(ii);
    }//GEN-LAST:event_jLabel6MouseEntered

    private void jLabel6MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel6MouseExited
          ImageIcon ii = new ImageIcon(getClass().getResource("/IMG/update1.png"));
        jLabel6.setIcon(ii);
    }//GEN-LAST:event_jLabel6MouseExited

    private void jLabel6MousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel6MousePressed
          ImageIcon ii = new ImageIcon(getClass().getResource("/IMG/update3.png"));
        jLabel6.setIcon(ii);
    }//GEN-LAST:event_jLabel6MousePressed

    private void jLabel6MouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel6MouseReleased
         ImageIcon ii = new ImageIcon(getClass().getResource("/IMG/update2.png"));
        jLabel6.setIcon(ii);
    }//GEN-LAST:event_jLabel6MouseReleased

    private void jLabel3MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel3MouseClicked
      itname.setText("");
      itprice.setText("");
    }//GEN-LAST:event_jLabel3MouseClicked

    private void jLabel2MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel2MouseClicked
         String itna = itname.getText();
         String itpr = itprice.getText();
        
         
         //blank
         if(itna.isEmpty()){
           add_pricename_error jf2 = new   add_pricename_error();
            jf2.show();
            
            jLabel2.setVisible(false);
            jLabel3.setVisible(false);
            jLabel4.setVisible(false);
            jLabel6.setVisible(false);
            
        }else if(itpr.isEmpty()){
             add_price_error jf2 = new   add_price_error();
            jf2.show();
            
            jLabel2.setVisible(false);
            jLabel3.setVisible(false);
            jLabel4.setVisible(false);
            jLabel6.setVisible(false);
            
       
        }else{
            
            //db
                String url = "jdbc:mysql://localhost:3306/coffee_shop";
            String user =  "root";
            String password = "1234";

            try {

                Class.forName("com.mysql.jdbc.Driver");
                Connection con = DriverManager.getConnection(url, user, password);
                Statement st = con.createStatement();
                st.executeUpdate("INSERT INTO items VALUES('"+itna+"','"+itpr+"')");

                  itname.setText("");
                  itprice.setText("");
                 
                
                  UserTableDataClear();
                
                   // data set to th table
                  UserTableDataSetter();
                
                
                
                

            } catch (Exception e) {
                System.out.println("DB Connection: "+e);
            }
                
               
        }
    }//GEN-LAST:event_jLabel2MouseClicked

    private void item_tableMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_item_tableMouseClicked
      DefaultTableModel table= (DefaultTableModel) item_table.getModel();
         int selectedRow = item_table.getSelectedRow();
         
         itname.setText(table.getValueAt(selectedRow, 0).toString());
         itprice.setText(table.getValueAt(selectedRow, 1).toString());
         
         
    }//GEN-LAST:event_item_tableMouseClicked

    private void jLabel6MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel6MouseClicked
    
         String itnaup = itname.getText();
         String itprup = itprice.getText();
        
        //db connection
            String url = "jdbc:mysql://localhost:3306/coffee_shop";
            String user =  "root";
            String password = "1234";
            try {
                Class.forName("com.mysql.jdbc.Driver");
                Connection con = DriverManager.getConnection(url, user, password);
                Statement st = con.createStatement();
                st.executeUpdate("UPDATE items SET itemname='"+itnaup+"',price='"+itprup+"' WHERE itemname='"+itnaup+"'");
                
               itname.setText("");
                itprice.setText("");
               
                 UserTableDataClear();
                
                   // data set to th table
                  UserTableDataSetter();

            } catch (Exception e) {
                System.out.println(e);
            }
        
       
    }//GEN-LAST:event_jLabel6MouseClicked

    private void jLabel4MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel4MouseClicked
         String itna = itname.getText();
        //db connection
            String url = "jdbc:mysql://localhost:3306/coffee_shop";
            String user =  "root";
            String password = "1234";
            try {
                Class.forName("com.mysql.jdbc.Driver");
                Connection con = DriverManager.getConnection(url, user, password);
                Statement st = con.createStatement();
                st.executeUpdate("DELETE FROM items WHERE itemname='"+itna+"'");
                
               itname.setText("");
                itprice.setText("");
              
                UserTableDataClear();
                
                   // data set to th table
                  UserTableDataSetter();
                

            } catch (Exception e) {
                System.out.println(e);
            }
        
    }//GEN-LAST:event_jLabel4MouseClicked

    private void jLabel5MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel5MouseEntered
        ImageIcon ii = new ImageIcon(getClass().getResource("/IMG/cut2.png"));
        jLabel5.setIcon(ii);
    }//GEN-LAST:event_jLabel5MouseEntered

    private void jLabel5MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel5MouseExited
          ImageIcon ii = new ImageIcon(getClass().getResource("/IMG/cut.png"));
        jLabel5.setIcon(ii);
    }//GEN-LAST:event_jLabel5MouseExited

    private void jLabel5MousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel5MousePressed
          ImageIcon ii = new ImageIcon(getClass().getResource("/IMG/cut3.png"));
        jLabel5.setIcon(ii);
    }//GEN-LAST:event_jLabel5MousePressed

    private void jLabel5MouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel5MouseReleased
          ImageIcon ii = new ImageIcon(getClass().getResource("/IMG/cut2.png"));
        jLabel5.setIcon(ii);
    }//GEN-LAST:event_jLabel5MouseReleased

    private void jLabel5MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel5MouseClicked
       System.exit(0);
    }//GEN-LAST:event_jLabel5MouseClicked

    private void itnameKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_itnameKeyReleased
       if (evt.getKeyCode()==KeyEvent.VK_ENTER){
     itprice.requestFocus();
      }
    }//GEN-LAST:event_itnameKeyReleased

    private void jLabel7MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel7MouseEntered
       ImageIcon ii = new ImageIcon(getClass().getResource("/IMG/back2.png"));
        jLabel7.setIcon(ii);
    }//GEN-LAST:event_jLabel7MouseEntered

    private void jLabel7MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel7MouseExited
       ImageIcon ii = new ImageIcon(getClass().getResource("/IMG/back1.png"));
        jLabel7.setIcon(ii);
    }//GEN-LAST:event_jLabel7MouseExited

    private void jLabel7MousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel7MousePressed
      ImageIcon ii = new ImageIcon(getClass().getResource("/IMG/back3.png"));
        jLabel7.setIcon(ii);
    }//GEN-LAST:event_jLabel7MousePressed

    private void jLabel7MouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel7MouseReleased
       ImageIcon ii = new ImageIcon(getClass().getResource("/IMG/back2.png"));
        jLabel7.setIcon(ii);
    }//GEN-LAST:event_jLabel7MouseReleased

    private void jLabel7MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel7MouseClicked
       billpage jf2 = new billpage();
        jf2.show();
    }//GEN-LAST:event_jLabel7MouseClicked

  
    

    
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(item_add.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(item_add.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(item_add.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(item_add.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new item_add().setVisible(true);
            }
        });
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel date;
    private javax.swing.JTable item_table;
    public static javax.swing.JTextField itname;
    private javax.swing.JTextField itprice;
    private javax.swing.JLabel jLabel1;
    public static javax.swing.JLabel jLabel2;
    public static javax.swing.JLabel jLabel3;
    public static javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    public static javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel times;
    // End of variables declaration//GEN-END:variables
}
